// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exo2EF.DbManager2;

#nullable disable

namespace exo2EF.Migrations
{
    [DbContext(typeof(DbHotel))]
    partial class DbHotelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("exo2EF.Model2.Chambre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NbLits")
                        .HasColumnType("int")
                        .HasColumnName("nombreDeLit");

                    b.Property<int>("Statut")
                        .HasMaxLength(15)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<double>("Tarif")
                        .HasColumnType("double")
                        .HasColumnName("tarif");

                    b.HasKey("Id");

                    b.ToTable("chambre");
                });

            modelBuilder.Entity("exo2EF.Model2.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("nom");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tel");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("prenom");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("exo2EF.Model2.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChambresId")
                        .HasColumnType("int")
                        .HasColumnName("Chambre_id");

                    b.Property<int>("ClientsId")
                        .HasColumnType("int")
                        .HasColumnName("Client_id");

                    b.Property<int>("StatutR")
                        .HasMaxLength(15)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ChambresId");

                    b.HasIndex("ClientsId");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("exo2EF.Model2.Reservation", b =>
                {
                    b.HasOne("exo2EF.Model2.Chambre", "Chambres")
                        .WithMany()
                        .HasForeignKey("ChambresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exo2EF.Model2.Client", "Clients")
                        .WithMany()
                        .HasForeignKey("ClientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chambres");

                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
